update=21/03/2018 14:06:34
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Amplifier_Audio
LibName2=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Amplifier_Buffer
LibName3=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Amplifier_Current
LibName4=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Amplifier_Difference
LibName5=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Amplifier_Instrumentation
LibName6=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Amplifier_Operational
LibName7=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Amplifier_Video
LibName8=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Analog
LibName9=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Analog_ADC
LibName10=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Analog_DAC
LibName11=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Analog_Switch
LibName12=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Audio
LibName13=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Battery_Management
LibName14=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Comparator
LibName15=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Connector_Generic
LibName16=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Connector_Generic_Shielded
LibName17=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Connector_Specialized
LibName18=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Converter_DCDC
LibName19=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/CPLD_Altera
LibName20=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/CPLD_Xilinx
LibName21=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/CPU
LibName22=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Device
LibName23=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Diode
LibName24=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Diode_Bridge
LibName25=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Diode_Laser
LibName26=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Display_Character
LibName27=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Display_Graphic
LibName28=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Driver_Display
LibName29=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Driver_FET
LibName30=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Driver_LED
LibName31=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Driver_Motor
LibName32=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Driver_Relay
LibName33=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/DSP_Freescale
LibName34=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/DSP_Microchip_DSPIC33
LibName35=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/DSP_Texas
LibName36=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/FPGA_Actel
LibName37=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/FPGA_Xilinx
LibName38=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/FPGA_Xilinx_Artix7
LibName39=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/FPGA_Xilinx_Kintex7
LibName40=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/FPGA_Xilinx_Spartan6
LibName41=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/FPGA_Xilinx_Virtex5
LibName42=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/FPGA_Xilinx_Virtex6
LibName43=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/FPGA_Xilinx_Virtex7
LibName44=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Graphic
LibName45=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Interface
LibName46=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Interface_CAN_LIN
LibName47=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Interface_CurrentLoop
LibName48=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Interface_Ethernet
LibName49=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Interface_Expansion
LibName50=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Interface_HID
LibName51=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Interface_LineDriver
LibName52=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Interface_Optical
LibName53=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Interface_Telecom
LibName54=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Interface_UART
LibName55=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Interface_USB
LibName56=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Isolator
LibName57=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Isolator_Analog
LibName58=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Jumper
LibName59=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/LED
LibName60=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Logic_74xgxx
LibName61=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Logic_74xx
LibName62=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Logic_CMOS_4000
LibName63=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Logic_CMOS_IEEE
LibName64=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Logic_LevelTranslator
LibName65=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Logic_Programmable
LibName66=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Logic_TTL_IEEE
LibName67=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_AnalogDevices
LibName68=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Atmel_8051
LibName69=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Atmel_ATMEGA
LibName70=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Atmel_ATTINY
LibName71=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Atmel_AVR
LibName72=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Cypress
LibName73=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Infineon
LibName74=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Intel
LibName75=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Microchip_PIC10
LibName76=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Microchip_PIC12
LibName77=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Microchip_PIC16
LibName78=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Microchip_PIC18
LibName79=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Microchip_PIC24
LibName80=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Microchip_PIC32
LibName81=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Microchip_SAME
LibName82=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Microchip_SAML
LibName83=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Module
LibName84=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_NXP_HC11
LibName85=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_NXP_Kinetis
LibName86=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_NXP_LPC
LibName87=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_NXP_S08
LibName88=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Parallax
LibName89=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_SiFive
LibName90=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_SiliconLabs
LibName91=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_ST_STM8
LibName92=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_ST_STM32
LibName93=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Texas
LibName94=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/MCU_Texas_MSP430
LibName95=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Mechanical
LibName96=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Memory_Controller
LibName97=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Memory_EEPROM
LibName98=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Memory_Flash
LibName99=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Memory_NVRAM
LibName100=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Memory_RAM
LibName101=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Memory_ROM
LibName102=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Memory_UniqueID
LibName103=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Motor
LibName104=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Oscillator
LibName105=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Potentiometer_Digital
LibName106=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/power
LibName107=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Power_Management
LibName108=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Power_Protection
LibName109=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Power_Supervisor
LibName110=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/pspice
LibName111=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Reference_Current
LibName112=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Reference_Voltage
LibName113=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Regulator_Controller
LibName114=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Regulator_Current
LibName115=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Regulator_Linear
LibName116=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Regulator_SwitchedCapacitor
LibName117=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Regulator_Switching
LibName118=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Relay
LibName119=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Relay_SolidState
LibName120=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/RF
LibName121=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/RF_AM_FM
LibName122=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/RF_Bluetooth
LibName123=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/RF_GPS
LibName124=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/RF_Mixer
LibName125=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/RF_Module
LibName126=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/RF_RFID
LibName127=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/RF_WiFi
LibName128=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/RF_ZigBee
LibName129=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Sensor
LibName130=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Sensor_Audio
LibName131=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Sensor_Current
LibName132=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Sensor_Gas
LibName133=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Sensor_Humidity
LibName134=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Sensor_Magnetic
LibName135=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Sensor_Motion
LibName136=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Sensor_MultiFunction
LibName137=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Sensor_Optical
LibName138=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Sensor_Pressure
LibName139=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Sensor_Proximity
LibName140=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Sensor_Temperature
LibName141=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Sensor_Touch
LibName142=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Sensor_Voltage
LibName143=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Switch
LibName144=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Timer
LibName145=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Timer_RTC
LibName146=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Transformer
LibName147=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Transistor_Array
LibName148=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Transistor_BJT
LibName149=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Transistor_FET
LibName150=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Transistor_IGBT
LibName151=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Triac_Thyristor
LibName152=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Valve
LibName153=C:/Users/Niko titi/Desktop/Audio_processor/Nouveau dossier/Video
LibName154=library/pcm1861
